version: "3.8"

services:
  todolist:
    image: caclm10/todolist-app:latest
    container_name: todolist-app
    restart: always
    ports:
      - "8200:3000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
